language: php

php:
  - 5.6

env:
  global:
    - PATH=$PATH:/home/travis/.composer/vendor/bin

install:
  - composer self-update

before_script:
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # Set sendmail so drush doesn't throw an error during site install.
  - echo "sendmail_path=`which true`" >> `php --ini | grep "Loaded Configuration" | awk '{print $4}'`
  # Create database.
  - mysql -e 'create database drupal'
  - composer create-project drupal-composer/drupal-project:7.x-dev test-site --stability dev --no-interaction
  - cd test-site
  # Install Drupal y target site.
  - composer require drush/drush:7.*
  - cd web
  - ../vendor/bin/drush si standard -y --db-url=mysql://travis:@127.0.0.1/drupal
  # Test latest commit on current branch.
  - git clone --branch=$TRAVIS_BRANCH https://github.com/$TRAVIS_REPO_SLUG.git sites/all/themes/atomium
  - ../vendor/bin/drush en atomium -y
  - ../vendor/bin/drush vset theme_default atomium
  - ../vendor/bin/drush dis overlay update -y
  - ../vendor/bin/drush cc all
  # Run Drush web server.
  - ../vendor/bin/drush --debug runserver :8888 > ~/debug.txt 2>&1 &
  - sleep 4s
  - chmod -R ug+w sites
  - cd sites/all/themes/atomium
  - composer install --prefer-dist
  - sed -e "s?%ROOT%?$TRAVIS_BUILD_DIR/test-site/web?g" --in-place phpunit.xml.dist
  - sed -e "s?%URL%?http://127.0.0.1:8888?g" --in-place phpunit.xml.dist

script:
  - ./vendor/bin/grumphp run
  - ./vendor/bin/phpunit

after_success:
  - cd $TRAVIS_BUILD_DIR/test-site/web
  - ../vendor/bin/drush vset theme_default bartik
  - ab -n 500 -kc 10 http://127.0.0.1:8888/
  - ../vendor/bin/drush vset theme_default atomium
  - ab -n 500 -kc 10 http://127.0.0.1:8888/
  - ../vendor/bin/drush en realistic_dummy_content devel -y
  - ../vendor/bin/drush en devel_generate -y
  - ../vendor/bin/drush generate-content 50
  - ../vendor/bin/drush vset theme_default bartik
  - ab -n 500 -kc 10 http://127.0.0.1:8888/
  - ../vendor/bin/drush vset theme_default atomium
  - ab -n 500 -kc 10 http://127.0.0.1:8888/

notifications:
  email: false
